name: ejercicios_pmdm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/img/foto_menu.jpg
  - assets/img/foto_ejercicio_2.jpg
  - assets/img/foto_logo_python.webp
  - assets/img/foto_logo_flutter.png
  - assets/img/foto_logo_java.webp
  - assets/img/foto_futbol.jpg
  - assets/img/foto_baloncesto.jpg
  - assets/img/foto_tenis.jpg
  - assets/img/foto_golf.jpg
  - assets/img/foto_surf.jpg
